# permissions for end users to view externalartifacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalartifacts-viewer-role
rules:
- apiGroups:
  - source.werf.io
  resources:
  - externalartifacts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.werf.io
  resources:
  - externalartifacts/status
  verbs:
  - get
