# permissions for end users to edit externalartifacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalartifact-editor-role
rules:
- apiGroups:
  - source.werf.io
  resources:
  - externalartifacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.werf.io
  resources:
  - externalartifacts/status
  verbs:
  - get
