# permissions for end users to view helmrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmrepository-viewer-role
rules:
- apiGroups:
  - source.werf.io
  resources:
  - helmrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.werf.io
  resources:
  - helmrepositories/status
  verbs:
  - get
