# permissions for end users to view helmcharts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmchart-viewer-role
rules:
- apiGroups:
  - source.werf.io
  resources:
  - helmcharts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.werf.io
  resources:
  - helmcharts/status
  verbs:
  - get
