apiVersion: source.werf.io/v1
kind: HelmChart
metadata:
  name: helmchart-sample
spec:
  chart: podinfo
  version: '6.x'
  sourceRef:
    kind: HelmRepository
    name: helmrepository-sample
  interval: 1m
  ignoreMissingValuesFiles: true
