apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: helmchart-sample-oci
spec:
  chart: stefanprodan/charts/podinfo
  version: '>=6.0.0 <7.0.0'
  sourceRef:
    kind: HelmRepository
    name: helmrepository-sample-oci
  interval: 1m
