apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/source.werf.io_gitrepositories.yaml
- bases/source.werf.io_helmrepositories.yaml
- bases/source.werf.io_helmcharts.yaml
- bases/source.werf.io_buckets.yaml
- bases/source.werf.io_ocirepositories.yaml
- bases/source.werf.io_externalartifacts.yaml
# +kubebuilder:scaffold:crdkustomizeresource
