
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: gitrepositories.source.fluxcd.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.url
    name: URL
    type: string
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[?(@.type=="Ready")].message
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: source.fluxcd.io
  names:
    kind: GitRepository
    listKind: GitRepositoryList
    plural: gitrepositories
    singular: gitrepository
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GitRepository is the Schema for the gitrepositories API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GitRepositorySpec defines the desired state of a Git repository.
          properties:
            interval:
              description: The interval at which to check for repository updates.
              type: string
            ref:
              description: The git reference to checkout and monitor for changes,
                defaults to master branch.
              properties:
                branch:
                  description: The git branch to checkout, defaults to master.
                  type: string
                commit:
                  description: The git commit sha to checkout, if specified tag filters
                    will be ignored.
                  type: string
                semver:
                  description: The git tag semver expression, takes precedence over
                    tag.
                  type: string
                tag:
                  description: The git tag to checkout, takes precedence over branch.
                  type: string
              type: object
            secretRef:
              description: The secret name containing the Git credentials. For HTTPS
                repositories the secret must contain username and password fields.
                For SSH repositories the secret must contain identity, identity.pub
                and known_hosts fields.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            sourceIgnore:
              description: SourceIgnore overrides the set of excluded patterns in
                the .sourceignore format (which is the same as .gitignore). If not
                provided, a default will be used, consult the documentation for your
                version to find out what those are.
              type: string
            timeout:
              description: The timeout for remote git operations like cloning, default
                to 20s.
              type: string
            url:
              description: The repository URL, can be a HTTP or SSH address.
              pattern: ^(http|https|ssh)://
              type: string
            verify:
              description: Verify OpenPGP signature for the commit that HEAD points
                to.
              properties:
                mode:
                  description: Mode describes what git object should be verified,
                    currently ('head').
                  enum:
                  - head
                  type: string
                secretRef:
                  description: The secret name containing the public keys of all trusted
                    git authors.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
              required:
              - mode
              type: object
          required:
          - interval
          - url
          type: object
        status:
          description: GitRepositoryStatus defines the observed state of a Git repository.
          properties:
            artifact:
              description: Artifact represents the output of the last successful repository
                sync.
              properties:
                lastUpdateTime:
                  description: LastUpdateTime is the timestamp corresponding to the
                    last update of this artifact.
                  format: date-time
                  type: string
                path:
                  description: Path is the local file path of this artifact.
                  type: string
                revision:
                  description: Revision is a human readable identifier traceable in
                    the origin source system. It can be a commit sha, git tag, a helm
                    index timestamp, a helm chart version, a checksum, etc.
                  type: string
                url:
                  description: URL is the HTTP address of this artifact.
                  type: string
              required:
              - path
              - url
              type: object
            conditions:
              items:
                description: SourceCondition contains condition information for a
                  source.
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the timestamp corresponding
                      to the last status change of this condition.
                    format: date-time
                    type: string
                  message:
                    description: Message is a human readable description of the details
                      of the last transition, complementing reason.
                    type: string
                  reason:
                    description: Reason is a brief machine readable explanation for
                      the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of ('True', 'False',
                      'Unknown').
                    type: string
                  type:
                    description: Type of the condition, currently ('Ready').
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            url:
              description: URL is the download link for the artifact output of the
                last repository sync.
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
