#name: test
#on:
#  workflow_dispatch:
#  pull_request:
#  push:
#    branches:
#      - 'main'
#      - 'release/**'
#jobs:
#  test-linux-amd64:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Test suite setup
#        uses: fluxcd/gha-workflows/.github/actions/setup-kubernetes@v0.4.0
#        with:
#          go-version: 1.25.x
#      - name: Run tests
#        env:
#          SKIP_COSIGN_VERIFICATION: true
#          TEST_AZURE_ACCOUNT_NAME: ${{ secrets.TEST_AZURE_ACCOUNT_NAME }}
#          TEST_AZURE_ACCOUNT_KEY: ${{ secrets.TEST_AZURE_ACCOUNT_KEY }}
#        run: make test
